on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
  steps:
    - uses: action/checkout@v2
    - name: Setup .NET SDK
    - uses: actions/setup-dotnet@v5.3.0
      with: 
        dotnet-verision: 8.0.x
    - name: Restore Dependency
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore
    
    
